### ISSUE TITLE
Are there any documents and tutorials about this repository?

### ISSUE THREAD

**Issue by GabrielLin** [Pelhans/pos_blstm#1]
Thanks.

**Comment by Pelhans** [comment]
I wrote lexical analysis(cws, pos, ner) based on this [CWS tutorial](https://github.com/yongyehuang/Tensorflow-Tutorial/blob/master/Tutorial_6%20-%20Bi-directional%20LSTM%20for%20sequence%20labeling%20(Chinese%20segmentation).ipynb). The difference between them(cws, pos, ner) is  the input and decode parts. So maybe that tutorial would be useful to you.
